apiVersion: v1
kind: Service
metadata:
  name: cert-process-service
spec:
  selector:
    app: handler
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
      - 10.210.12.231
