apiVersion: v1
kind: Service
metadata:
  name: cert-service
spec:
  selector:
    app: cert-client
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
  externalIPs:
    - 10.210.12.231
